name = "nextjs-prisma-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "nextjs-prisma-app-db"
database_id = "242a5c26-18a8-4e98-98cf-0f5d86d764af"
